<?php namespace App\Libraries;

class PostSeeder
{
    public static function getPostsData($userId, $categories, $langViId, $langEnId)
    {
        $now = date('Y-m-d H:i:s');
        $baseUrl = base_url();

        return [
            // ==========================================
            // ── TIẾNG VIỆT (10 BÀI CHO 5 CHỦ ĐỀ) ──
            // ==========================================

            // 1. CHỦ ĐỀ: VẬN TẢI HÀNG KHÔNG (Air Freight)
            [
                'lang_id' => $langViId,
                'category_id' => $categories['air_vi'],
                'user_id' => $userId,
                'title' => 'Dịch Vụ Vận Tải Hàng Không Hỏa Tốc Quốc Tế Cùng TOP BEST GLOBAL',
                'slug' => 'van-tai-hang-khong-hoa-toc-quoc-te-topbestglobal',
                'summary' => 'Giải pháp vận chuyển hàng không ưu tiên với thời gian bay chỉ 24-48 giờ tới các trung tâm kinh tế lớn tại Mỹ, Châu Âu, Nhật Bản và Hàn Quốc.',
                'content' => '<p><strong>TOP BEST GLOBAL Express Air Cargo</strong> cung cấp giải pháp vận tải hàng không chuyên tuyến hỏa tốc, tối ưu hóa tuyệt đối thời gian giao hàng dành cho các kiện hàng cấp bách, hàng mẫu và dược phẩm y tế.</p><h3>Ưu thế vượt trội của dịch vụ Air Freight</h3><ul><li>Cam kết chỗ ổn định (BSA) với hơn 15 hãng hàng không quốc tế hàng đầu.</li><li>Dịch vụ nhận hàng tận nơi và giao hàng tận tay (Door-to-Door) toàn cầu.</li><li>Xử lý thủ tục hải quan sân bay Nội Bài (HAN) và Tân Sơn Nhất (SGN) trong vòng 2 giờ.</li></ul><p>Liên hệ ngay bộ phận Air Freight TOP BEST GLOBAL để nhận lịch bay và báo giá cước ưu đãi trong ngày.</p>',
                'keywords' => 'air freight, van tai hang khong, van chuyen hoa toc, logistics, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/hero_banner.jpg',
                'image_description' => 'Vận tải hàng không TOP BEST GLOBAL',
                'pageviews' => 184,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-1 hour')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langViId,
                'category_id' => $categories['air_vi'],
                'user_id' => $userId,
                'title' => 'Giải Pháp Vận Chuyển Linh Kiện Điện Tử & Hàng Công Nghệ Cao Đường Hàng Không',
                'slug' => 'van-chuyen-linh-kien-dien-tu-hang-khong',
                'summary' => 'Quy chuẩn đóng gói chống tĩnh điện, kiểm soát độ ẩm và bảo hiểm 100% giá trị cho chuỗi cung ứng linh kiện bán dẫn và vi mạch điện tử.',
                'content' => '<p>Ngành công nghiệp bán dẫn và điện tử đòi hỏi tiêu chuẩn vận chuyển khắt khe bậc nhất. TOP BEST GLOBAL tự hào mang đến giải pháp logistics chuyên biệt cho hàng công nghệ cao (High-Tech Cargo).</p><h3>Tiêu chuẩn an toàn hàng đầu</h3><ul><li>Đóng gói chuẩn ESD chống phóng tĩnh điện và giảm chấn đa lớp.</li><li>Thiết bị cảm biến theo dõi nhiệt độ, độ ẩm và rung lắc theo thời gian thực.</li><li>Quy trình bốc xếp ưu tiên tại kho hàng hàng không (TCS, NCTS, ASc).</li></ul><p>TOP BEST GLOBAL đồng hành cùng hơn 50 doanh nghiệp FDI điện tử hàng đầu tại Việt Nam.</p>',
                'keywords' => 'linh kien dien tu, high tech logistics, ban dan, air freight, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/hero_banner.jpg',
                'image_description' => 'Vận chuyển linh kiện điện tử',
                'pageviews' => 142,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-2 hours')),
                'updated_at' => $now
            ],

            // 2. CHỦ ĐỀ: VẬN TẢI ĐƯỜNG BIỂN (Sea Freight)
            [
                'lang_id' => $langViId,
                'category_id' => $categories['sea_vi'],
                'user_id' => $userId,
                'title' => 'TOP BEST GLOBAL Mở Rộng Tuyến Vận Tải Đường Biển Quốc Tế Đi Bắc Mỹ & Châu Âu 2026',
                'slug' => 'topbestglobal-mo-rong-tuyen-van-tai-duong-bien-quoc-te-2026',
                'summary' => 'Nhằm đáp ứng nhu cầu xuất nhập khẩu tăng cao, TOP BEST GLOBAL chính thức mở rộng thêm 5 hải trình FCL/LCL kết nối trực tiếp các cảng lớn tại Việt Nam tới thị trường Mỹ và EU.',
                'content' => '<p><strong>TOP BEST GLOBAL Corporation</strong> trân trọng thông báo chính thức mở rộng thêm 5 tuyến hải trình vận tải đường biển quốc tế (FCL &amp; LCL) kết nối trực tiếp từ các cụm cảng Hải Phòng, Đà Nẵng, Cát Lái (TP.HCM) tới các trung tâm kinh tế lớn tại Bắc Mỹ và Châu Âu.</p><h3>1. Giải pháp vận chuyển tối ưu thời gian và chi phí</h3><p>Với năng lực hợp tác cùng hơn 20 hãng tàu lớn trên thế giới, TOP BEST GLOBAL cam kết mang đến giá cước cạnh tranh nhất, đảm bảo lịch tàu cố định hàng tuần và thời gian transit rút ngắn từ 3 - 5 ngày so với tiêu chuẩn thông thường.</p><h3>2. Dịch vụ trọn gói Door-to-Door</h3><ul><li>Hỗ trợ khai báo thủ tục thông quan hải quan điện tử 24/7.</li><li>Hệ thống kho bãi ngoại quan và trung chuyển hiện đại tại các cửa ngõ giao thương.</li><li>Giám sát hành trình đơn hàng theo thời gian thực (Real-time tracking).</li></ul>',
                'keywords' => 'van tai duong bien, fcl, lcl, ocean freight, logistics, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/fcl_service.jpg',
                'image_description' => 'Vận tải đường biển FCL LCL',
                'pageviews' => 256,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-3 hours')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langViId,
                'category_id' => $categories['sea_vi'],
                'user_id' => $userId,
                'title' => 'Tối Ưu Chi Phí Gom Hàng Lẻ LCL Cho Doanh Nghiệp Xuất Khẩu Vừa Và Nhỏ',
                'slug' => 'toi-uu-chi-phi-gom-hang-le-lcl-xuat-khau',
                'summary' => 'Giải pháp gom hàng lẻ định kỳ hàng tuần giúp doanh nghiệp SME tiết kiệm tới 35% chi phí logistics mà vẫn đảm bảo tiến độ giao nhận đúng hạn.',
                'content' => '<p>Dịch vụ LCL Consolidation của TOP BEST GLOBAL cho phép các nhà xuất khẩu vừa và nhỏ ghép hàng an toàn, minh bạch chi phí và tiếp cận biểu cước trực tiếp từ các hãng tàu hàng đầu.</p><h3>Lợi ích vượt trội của dịch vụ LCL TOP BEST GLOBAL</h3><ul><li>Kho gom hàng CFS riêng biệt tại Cát Lái và Hải Phòng với quy trình kiểm soát mã vạch tự động.</li><li>Lịch đóng container hàng tuần cố định, không lo trễ chuyến.</li><li>Hỗ trợ làm C/O, kiểm dịch thực vật và kiểm tra chuyên ngành trọn gói.</li></ul>',
                'keywords' => 'gom hang le, lcl consolidation, van tai bien, sme logistics',
                'image_url' => $baseUrl . '/assets/themes/suntransco/lcl_service.jpg',
                'image_description' => 'Dịch vụ gom hàng lẻ LCL',
                'pageviews' => 198,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-4 hours')),
                'updated_at' => $now
            ],

            // 3. CHỦ ĐỀ: VẬN TẢI NỘI ĐỊA (Inland Freight)
            [
                'lang_id' => $langViId,
                'category_id' => $categories['inland_vi'],
                'user_id' => $userId,
                'title' => 'Mạng Lưới Vận Tải Đường Bộ Bắc Nam 24/7 Tích Hợp GPS Thời Gian Thực',
                'slug' => 'mang-luoi-van-tai-duong-bo-bac-nam-gps',
                'summary' => 'Đội xe vận tải đường bộ hơn 150 đầu kéo và xe tải đa tải trọng vận hành liên tục trục Bắc Nam, cam kết giao hàng an toàn và đúng lịch trình.',
                'content' => '<p>TOP BEST GLOBAL cung cấp dịch vụ vận tải nội địa đường bộ với mạng lưới trạm điều vận trải dài từ Hà Nội, Đà Nẵng, Quy Nhơn đến TP.HCM và Cần Thơ.</p><h3>Năng lực vận tải đường bộ TOP BEST GLOBAL</h3><ul><li>100% phương tiện trang bị định vị GPS và cảm biến nhiệt độ thùng xe.</li><li>Đội ngũ tài xế chuyên nghiệp, giàu kinh nghiệm vận chuyển hàng quá khổ, quá tải.</li><li>Bảo hiểm trách nhiệm hàng hóa lên tới 10 tỷ VNĐ mỗi chuyến vận chuyển.</li></ul>',
                'keywords' => 'van tai duong bo, bac nam, trucking, gps tracking, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/about_banner.jpg',
                'image_description' => 'Đội xe vận tải đường bộ',
                'pageviews' => 165,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-5 hours')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langViId,
                'category_id' => $categories['inland_vi'],
                'user_id' => $userId,
                'title' => 'Giải Pháp Vận Tải Đa Phương Thức: Kết Nối Cảng Biển, Đường Sắt & Đường Bộ',
                'slug' => 'giai-phap-van-tai-da-phuong-thuc-viet-nam',
                'summary' => 'Tích hợp linh hoạt giữa đường bộ, đường sắt liên vận và đường thủy nội địa giúp cắt giảm 20% lượng phát thải CO2 và tối ưu hóa chi phí logistics.',
                'content' => '<p>Vận tải đa phương thức (Multimodal Transport) là chìa khóa then chốt giúp tối ưu hóa chuỗi cung ứng xanh và bền vững. TOP BEST GLOBAL kết nối nhịp nhàng giữa cảng biển nước sâu và các trung tâm logistics vệ tinh.</p><h3>Các mô hình đa phương thức tiêu biểu</h3><ul><li>Đường biển kết hợp đường sắt liên vận quốc tế đi Trung Quốc và Châu Âu.</li><li>Đường thủy sà lan kết nối cụm cảng Cái Mép - Thị Vải với các khu công nghiệp Bình Dương, Đồng Nai.</li><li>Phân phối chặng cuối (Last-mile delivery) bằng đội xe tải chuyên dụng.</li></ul>',
                'keywords' => 'da phuong thuc, multimodal, van tai xanh, green logistics, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/fcl_service.jpg',
                'image_description' => 'Vận tải đa phương thức',
                'pageviews' => 120,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-6 hours')),
                'updated_at' => $now
            ],

            // 4. CHỦ ĐỀ: KHO BÃI & CFS (Warehousing)
            [
                'lang_id' => $langViId,
                'category_id' => $categories['warehousing_vi'],
                'user_id' => $userId,
                'title' => 'Hệ Thống Kho Bãi CFS 20.000m² Hiện Đại Tại Cửa Ngõ TP.HCM & Hải Phòng',
                'slug' => 'he-thong-kho-bai-cfs-hien-dai-topbestglobal',
                'summary' => 'Hạ tầng kho bãi đạt chuẩn quốc tế với hệ thống giá kệ Selective đa tầng, sàn chịu lực cao và kiểm soát an ninh camera 24/7.',
                'content' => '<p>Hệ thống trung tâm phân phối và kho ngoại quan CFS của TOP BEST GLOBAL tọa lạc tại các vị trí chiến lược gần kề cao tốc và cụm cảng quốc tế, tạo điều kiện thuận lợi nhất cho luân chuyển hàng hóa xuất nhập khẩu.</p><h3>Tiêu chuẩn kho bãi TOP BEST GLOBAL</h3><ul><li>Tổng diện tích hơn 20.000m² có mái che, sàn phẳng không bụi epoxy.</li><li>Trang bị hệ thống PCCC tự động Sprinkler và camera giám sát 100% diện tích.</li><li>Cung cấp đầy đủ dịch vụ đóng gói, dán nhãn (labeling), phân loại và cross-docking.</li></ul>',
                'keywords' => 'kho bai, cfs, warehousing, luu kho, dong goi, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/about_banner.jpg',
                'image_description' => 'Hệ thống kho CFS TOP BEST GLOBAL',
                'pageviews' => 175,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-7 hours')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langViId,
                'category_id' => $categories['warehousing_vi'],
                'user_id' => $userId,
                'title' => 'Ứng Dụng Phần Mềm Quản Lý Kho WMS Tự Động Hóa Quản Lý Tồn Kho',
                'slug' => 'ung-dung-phan-mem-quan-ly-kho-wms',
                'summary' => 'Nền tảng số hóa WMS cho phép khách hàng tra cứu tồn kho thực tế, lịch sử xuất nhập và quét mã vạch Barcode/RFID theo thời gian thực.',
                'content' => '<p>Công nghệ quản trị kho thông minh Warehouse Management System (WMS) tại TOP BEST GLOBAL giúp xóa bỏ sai sót thủ công, nâng cao tốc độ soạn hàng lên 300% và cung cấp dữ liệu báo cáo minh bạch cho chủ hàng.</p><h3>Tính năng nổi bật của WMS</h3><ul><li>Quản lý vị trí hàng hóa theo tọa độ 3D và thuật toán gợi ý vị trí lưu kho tối ưu.</li><li>Tích hợp API kết nối trực tiếp với hệ thống ERP của doanh nghiệp khách hàng.</li><li>Báo cáo tự động lượng tồn kho an toàn và cảnh báo hạn sử dụng sản phẩm.</li></ul>',
                'keywords' => 'phan mem wms, quan ly ton kho, smart warehouse, so hoa kho, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/hero_banner.jpg',
                'image_description' => 'Quản trị kho thông minh WMS',
                'pageviews' => 150,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-8 hours')),
                'updated_at' => $now
            ],

            // 5. CHỦ ĐỀ: THỦ TỤC HẢI QUAN (Customs Clearance)
            [
                'lang_id' => $langViId,
                'category_id' => $categories['customs_vi'],
                'user_id' => $userId,
                'title' => 'Quy Trình Thông Quan Hải Quan Điện Tử 24/7 Dành Cho Doanh Nghiệp FDI',
                'slug' => 'quy-trinh-thong-quan-hai-quan-dien-tu-fdi',
                'summary' => 'Đội ngũ chuyên viên đại lý hải quan TOP BEST GLOBAL hỗ trợ hoàn tất tờ khai VNACCS/VCIS, xin giấy phép chuyên ngành và thông quan nhanh trong ngày.',
                'content' => '<p>Thủ tục hải quan là khâu trọng yếu quyết định tiến độ chuỗi cung ứng. Là đại lý hải quan được Tổng cục Hải quan công nhận, TOP BEST GLOBAL đại diện doanh nghiệp thực hiện toàn bộ các nghĩa vụ thủ tục XNK an toàn, đúng luật.</p><h3>Dịch vụ hải quan chuyên nghiệp</h3><ul><li>Khai báo tờ khai điện tử qua hệ thống VNACCS/VCIS cho mọi loại hình: Kinh doanh, Gia công, SXXK, EPE.</li><li>Hỗ trợ hoàn thuế, báo cáo quyết toán hải quan định kỳ cuối năm.</li><li>Tư vấn và thực hiện thủ tục kiểm dịch, công bố hợp quy, kiểm tra an toàn thực phẩm.</li></ul>',
                'keywords' => 'thong quan hai quan, dai ly hai quan, vnaccs, fdi logistics, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/lcl_service.jpg',
                'image_description' => 'Dịch vụ thông quan hải quan',
                'pageviews' => 210,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-9 hours')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langViId,
                'category_id' => $categories['customs_vi'],
                'user_id' => $userId,
                'title' => 'Tối Ưu Thuế Xuất Nhập Khẩu & Phân Loại Mã HS Code Chính Xác',
                'slug' => 'toi-uu-thue-xuat-nhap-khau-ma-hs-code',
                'summary' => 'Tư vấn áp dụng biểu thuế ưu đãi đặc biệt theo các hiệp định thương mại tự do EVFTA, CPTPP, RCEP nhằm tiết kiệm tối đa chi phí thuế nhập khẩu.',
                'content' => '<p>Xác định chính xác mã HS Code là yếu tố quyết định mức thuế suất và tránh các rủi ro phạt hành chính do khai sai mã hàng. TOP BEST GLOBAL cung cấp giải pháp tư vấn phân loại hàng hóa chuyên sâu kết hợp công nghệ AI tra cứu biểu thuế mới nhất.</p><h3>Lợi ích khi chuẩn hóa mã HS cùng TOP BEST GLOBAL</h3><ul><li>Tận dụng tối đa ưu đãi thuế quan từ các hiệp định FTA với form C/O phù hợp (Form E, Form D, Form EUR.1).</li><li>Hạn chế nguy cơ ấn định thuế hoặc tham vấn giá sau thông quan.</li><li>Xây dựng cơ sở dữ liệu phân loại hàng hóa đồng bộ cho doanh nghiệp lâu dài.</li></ul>',
                'keywords' => 'ma hs code, bieu thue xuat nhap khau, evfta, cptpp, tu van hai quan, topbestglobal',
                'image_url' => $baseUrl . '/assets/themes/suntransco/about_banner.jpg',
                'image_description' => 'Tư vấn phân loại mã HS',
                'pageviews' => 189,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-10 hours')),
                'updated_at' => $now
            ],

            // ==========================================
            // ── ENGLISH (10 POSTS FOR 5 TOPICS) ──
            // ==========================================

            // 1. TOPIC: AIR FREIGHT
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['air_en'],
                'user_id' => $userId,
                'title' => 'Next-Day Express Air Cargo Services Across Global Hubs',
                'slug' => 'next-day-express-air-cargo-global-hubs',
                'summary' => 'TOP BEST GLOBAL expands direct air charter and express cargo space allocations to ensure 24 to 48 hours delivery across North America, Europe, and Asia-Pacific.',
                'content' => '<p>TOP BEST GLOBAL provides priority air freight solutions designed for high-value electronics, pharmaceuticals, and urgent manufacturing components.</p><h3>Key Air Freight Advantages</h3><ul><li>Guaranteed blocked space agreements (BSA) with premier international airlines.</li><li>Seamless customs clearance at major international airports.</li><li>Complete door-to-door temperature-controlled cold chain logistics.</li></ul>',
                'keywords' => 'express air cargo, air freight, cold chain, logistics, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/hero_banner.jpg',
                'image_description' => 'Express Air Cargo',
                'pageviews' => 135,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-1 hour')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['air_en'],
                'user_id' => $userId,
                'title' => 'High-Tech Semiconductor & Electronics Air Freight Protocol',
                'slug' => 'high-tech-semiconductor-electronics-air-freight',
                'summary' => 'Specialized anti-static packaging, shock-vibration monitoring, and bonded airport tarmac handling for precision tech components.',
                'content' => '<p>Semiconductor manufacturing supply chains demand zero-defect transport. TOP BEST GLOBAL implements aerospace-grade cargo protection protocols across all key air routes.</p><h3>Certified High-Tech Cargo Features</h3><ul><li>Full ESD protective packaging compliant with MIL-STD-1686.</li><li>Real-time IoT data loggers tracking tilt, temperature, and G-force impact.</li><li>White-glove priority handling at tarmac and airport freight terminals.</li></ul>',
                'keywords' => 'semiconductor logistics, high-tech cargo, air freight, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/hero_banner.jpg',
                'image_description' => 'High Tech Air Freight',
                'pageviews' => 110,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-2 hours')),
                'updated_at' => $now
            ],

            // 2. TOPIC: SEA FREIGHT
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['sea_en'],
                'user_id' => $userId,
                'title' => 'TOP BEST GLOBAL Expands Global Maritime Logistics Network to North America & Europe',
                'slug' => 'topbestglobal-expands-global-maritime-logistics-network-2026',
                'summary' => 'To meet surging international supply chain demands, TOP BEST GLOBAL launches 5 new direct FCL and LCL shipping routes connecting major Vietnamese ports with USA and Europe.',
                'content' => '<p><strong>TOP BEST GLOBAL Corporation</strong> is proud to announce the strategic expansion of 5 direct ocean freight routes (FCL &amp; LCL), directly linking major Vietnamese ports (Hai Phong, Da Nang, Cat Lai) to top-tier commercial hubs across North America and Europe.</p><h3>1. Optimized Cost & Accelerated Transit Times</h3><p>Leveraging deep strategic partnerships with over 20 top global shipping lines, TOP BEST GLOBAL provides highly competitive freight rates, reliable weekly vessel departures, and reduced transit turnaround times by up to 5 days.</p><h3>2. Comprehensive End-to-End Solutions</h3><ul><li>Full digital customs clearance and documentation services available 24/7.</li><li>Modern bonded warehousing and regional distribution hubs.</li><li>Real-time cargo tracking and dedicated multimodal logistics management.</li></ul>',
                'keywords' => 'ocean freight, logistics, supply chain, fcl, lcl, shipping, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/fcl_service.jpg',
                'image_description' => 'TOP BEST GLOBAL Global Maritime Logistics',
                'pageviews' => 160,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-3 hours')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['sea_en'],
                'user_id' => $userId,
                'title' => 'LCL Consolidation Strategies for Cost-Effective SME Global Shipping',
                'slug' => 'lcl-consolidation-strategies-sme-shipping',
                'summary' => 'Weekly scheduled ocean consolidation boxes helping small and mid-sized exporters cut overseas freight spend by up to 35%.',
                'content' => '<p>TOP BEST GLOBAL LCL Consolidation provides predictable weekly sailing schedules, transparent pricing with no hidden destination fees, and guaranteed cargo security.</p><h3>Why Choose TOP BEST GLOBAL LCL</h3><ul><li>Dedicated CFS consolidation centers in Ho Chi Minh City and Hai Phong.</li><li>Automated barcode pallet tracking and moisture-resistant container lining.</li><li>Integrated customs clearance and Certificate of Origin (C/O) issuance.</li></ul>',
                'keywords' => 'lcl consolidation, ocean shipping, sme freight, container logistics, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/lcl_service.jpg',
                'image_description' => 'LCL Consolidation',
                'pageviews' => 125,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-4 hours')),
                'updated_at' => $now
            ],

            // 3. TOPIC: INLAND FREIGHT
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['inland_en'],
                'user_id' => $userId,
                'title' => 'Cross-Country Trucking Network with Real-Time GPS Telematics',
                'slug' => 'cross-country-trucking-network-gps-telematics',
                'summary' => 'Operating a modern fleet of 150+ heavy trucks and container tractors ensuring seamless 24/7 North-South transportation corridors.',
                'content' => '<p>TOP BEST GLOBAL delivers dependable inland trucking services linking international deep-water seaports with key industrial parks across Vietnam.</p><h3>Fleet Capabilities & Quality Guarantees</h3><ul><li>Real-time GPS routing, speed control, and electronic seal security.</li><li>Dedicated heavy-lift and oversize project cargo transport teams.</li><li>Full-coverage cargo insurance up to $500,000 per shipment.</li></ul>',
                'keywords' => 'inland freight, trucking vietnam, cross country shipping, gps tracking, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/about_banner.jpg',
                'image_description' => 'Inland Trucking Network',
                'pageviews' => 118,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-5 hours')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['inland_en'],
                'user_id' => $userId,
                'title' => 'Multimodal Transportation: Rail, Inland Waterway, and Highway Integration',
                'slug' => 'multimodal-transportation-rail-waterway-highway',
                'summary' => 'Driving eco-friendly supply chain optimization with synchronized barge feeder and international cross-border rail connections.',
                'content' => '<p>Combine maritime barging, block trains, and highway trucking to achieve lower freight costs and reduce supply chain carbon footprint by over 20%.</p><h3>Multimodal Operational Highlights</h3><ul><li>Cai Mep deep seaport barge shuttle to inland container depots (ICDs).</li><li>Cross-border international rail freight into China and Central Asia.</li><li>Optimized last-mile urban delivery fleet.</li></ul>',
                'keywords' => 'multimodal transport, rail freight, green logistics, barge feeder, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/fcl_service.jpg',
                'image_description' => 'Multimodal Transport',
                'pageviews' => 95,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-6 hours')),
                'updated_at' => $now
            ],

            // 4. TOPIC: WAREHOUSING
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['warehousing_en'],
                'user_id' => $userId,
                'title' => 'Modern 20,000 sqm Bonded & CFS Warehousing Infrastructure',
                'slug' => 'modern-bonded-cfs-warehousing-infrastructure',
                'summary' => 'Strategic logistics hubs equipped with heavy-duty multi-tier selective racking, dust-free epoxy floors, and round-the-clock CCTV surveillance.',
                'content' => '<p>TOP BEST GLOBAL CFS and bonded warehouse facilities are strategically located along major industrial arteries and port gateways for rapid inventory turns.</p><h3>Facility Specifications</h3><ul><li>Over 20,000 sqm covered storage with advanced automatic sprinkler fire protection.</li><li>Certified customs bonded area for duty-deferred international transshipments.</li><li>Value-added services: custom palletizing, shrink wrapping, kitting, and labeling.</li></ul>',
                'keywords' => 'warehousing, cfs warehouse, bonded storage, distribution center, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/about_banner.jpg',
                'image_description' => 'CFS Warehouse Infrastructure',
                'pageviews' => 140,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-7 hours')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['warehousing_en'],
                'user_id' => $userId,
                'title' => 'Smart Warehouse Management System (WMS) for Real-Time Inventory Control',
                'slug' => 'smart-wms-real-time-inventory-control',
                'summary' => 'Cloud-native WMS integration providing transparent SKU visibility, barcode verification, and automated replenishment alerts.',
                'content' => '<p>Transform your inventory visibility with TOP BEST GLOBAL intelligent WMS platform, boosting picking precision to 99.98% and streamlining order fulfillment.</p><h3>WMS Capabilities</h3><ul><li>3D warehouse slotting optimization and dynamic pick-path calculation.</li><li>Direct API/EDI integration into SAP, Oracle, and enterprise ERP platforms.</li><li>Automated batch tracking, expiry monitoring, and FIFO/FEFO execution.</li></ul>',
                'keywords' => 'smart wms, inventory management, logistics technology, warehouse automation, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/hero_banner.jpg',
                'image_description' => 'Smart WMS Platform',
                'pageviews' => 112,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-8 hours')),
                'updated_at' => $now
            ],

            // 5. TOPIC: CUSTOMS CLEARANCE
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['customs_en'],
                'user_id' => $userId,
                'title' => '24/7 Digital Customs Clearance Services for FDI Enterprises',
                'slug' => 'digital-customs-clearance-fdi-enterprises',
                'summary' => 'Licensed customs brokerage team accelerating VNACCS/VCIS declarations, specialized import licenses, and same-day cargo release.',
                'content' => '<p>Navigating customs regulations is critical to supply chain velocity. TOP BEST GLOBAL acts as your authorized customs broker, managing compliant entry and exit procedures across all ports.</p><h3>Comprehensive Brokerage Services</h3><ul><li>Electronic declaration processing for commercial, processing, and export manufacturing (EPE) regimes.</li><li>Duty drawback support and annual customs reconciliation reports.</li><li>Specialized inspection management: phytosanitary, quarantine, and quality certification.</li></ul>',
                'keywords' => 'customs clearance, customs broker, vnaccs, fdi trade compliance, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/lcl_service.jpg',
                'image_description' => 'Customs Clearance Services',
                'pageviews' => 168,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-9 hours')),
                'updated_at' => $now
            ],
            [
                'lang_id' => $langEnId,
                'category_id' => $categories['customs_en'],
                'user_id' => $userId,
                'title' => 'HS Code Tariff Optimization & FTA Duty Savings Consultation',
                'slug' => 'hs-code-tariff-optimization-fta-duty-savings',
                'summary' => 'Maximizing tariff preferences under EVFTA, CPTPP, and RCEP agreements to optimize import duty costs and eliminate regulatory audit risks.',
                'content' => '<p>Accurate HS Code classification is key to claiming legitimate preferential tariff rates under Free Trade Agreements while preventing costly penalties.</p><h3>Trade Compliance Advantages</h3><ul><li>FTA origin rule verification and proper C/O form determination (Form E, Form D, EUR.1).</li><li>Pre-clearance customs rulings and post-clearance audit advisory.</li><li>Harmonized corporate product classification database management.</li></ul>',
                'keywords' => 'hs code, tariff classification, evfta, cptpp, customs consulting, top best global',
                'image_url' => $baseUrl . '/assets/themes/suntransco/about_banner.jpg',
                'image_description' => 'HS Code Optimization',
                'pageviews' => 145,
                'post_type' => 'article',
                'status' => 1,
                'visibility' => 1,
                'is_scheduled' => 0,
                'created_at' => date('Y-m-d H:i:s', strtotime('-10 hours')),
                'updated_at' => $now
            ]
        ];
    }
}
